# Use an official Node runtime as a parent image
#FROM node:14 as builder
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any dependencies
RUN npm install

# Bundle app source inside Docker image
COPY . .

# Build the React app
RUN npm run build

# Install serve to run the app
RUN npm install -g serve

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app
CMD ["serve", "-s", "build", "-l", "3000"]